export function installSymfonyTwigAPI(engine, options = {}) {
  const {
    Routing,
    pathGenerator,
    uxIconResolver,
    iconResolver
  } = options;

  const resolvePath =
    typeof pathGenerator === 'function'
      ? pathGenerator
      : typeof Routing?.generate === 'function'
        ? (route, params = {}) => {
            const safeParams = { ...params };
            delete safeParams._keys;
            return Routing.generate(route, safeParams);
          }
        : null;

  if (resolvePath) {
    engine.registerFunction('path', resolvePath);
  }

  const resolveIcon =
    typeof uxIconResolver === 'function'
      ? uxIconResolver
      : typeof iconResolver === 'function'
        ? iconResolver
        : null;

  if (resolveIcon) {
    engine.registerFunction('ux_icon', resolveIcon);
  }

  return engine;
}

/**
 * Attempt to auto-detect and load the FOS JS Routing bundle, then install
 * the `path()` function into the engine.
 *
 * This tries, in order:
 *   1. Dynamic import of 'fos-routing' (the npm shim)
 *   2. fetch() of '/js/fos_js_routes.json' (plain JSON — no JS module wrapper)
 *   3. Calls Routing.setData(data) and registers path() on the engine.
 *
 * The JSON file is generated by:
 *   fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
 *
 * If either step fails (bundle not installed, or route file not present),
 * it silently skips — path() will throw a clear error at render time if called.
 *
 * @param {object} engine - twig-browser engine
 * @param {object} [options] - same options as installSymfonyTwigAPI
 * @param {string} [options.routesUrl='/js/fos_js_routes.json'] - URL to the JSON routes file
 * @returns {Promise<boolean>} true if routing was successfully wired
 */
export async function autoInstallFosRouting(engine, options = {}) {
  const { routesUrl = '/js/fos_js_routes.json', ...rest } = options;
  try {
    const { default: Routing } = await import('fos-routing');
    const response = await fetch(routesUrl);
    if (!response.ok) throw new Error(`Failed to fetch routes: ${response.status}`);
    const routingData = await response.json();
    Routing.setData(routingData);
    installSymfonyTwigAPI(engine, { ...rest, Routing });
    return true;
  } catch {
    // fos-routing not available — path() will throw at render time if called
    return false;
  }
}
